### ISSUE TITLE
[AVM Module Issue]: Duplicate Private Link service connection names in all modules

### ISSUE THREAD

**Issue by tyconsulting** [Azure/bicep-registry-modules#1042]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

Other, as defined below...

### (Optional) Module Name if not listed above

All modules that create Private Endpoints

### Description

When multiple private endpoints are defined, the PL service connection name are the same:
![image](https://github.com/Azure/bicep-registry-modules/assets/11845994/e5dc59d8-31cd-4bc3-a4e0-51b5636ffb58)

To fix this bug, this is what I have done:

1. in the module calling the PE module, extend the `privateEndpointType` by adding an additional property:

```Bicep
  @description('Optional. The name of the Private Link Service Connection.')
  privateLinkServiceConnectionName: string?
```

2. When calling the PE module, update the `name` property inside `privateLinkServiceConnections` to `name: privateEndpoint.?privateLinkServiceConnectionName ?? '${name}-${index}'` i.e.

![image](https://github.com/Azure/bicep-registry-modules/assets/11845994/714a1a6d-ea1f-4759-a186-abf76a7c719c)

AND

![image](https://github.com/Azure/bicep-registry-modules/assets/11845994/6d9f0156-aad1-45da-98f6-6da2ddb3cfbd)

This will allow me to give it a more meaningful name if required, and if I don't specify a name, a numeric character will append to the end of the name (`'${name}-${index}'`)

This is the end result:

![image](https://github.com/Azure/bicep-registry-modules/assets/11845994/d6ec3b11-0a0f-47c7-bd50-bf161b26f27c)

**Comment by tyconsulting** [comment]
Hi @segraef @AlexanderSehr this is also related to the multiple PE discussion we had few days ago (#962).

**Comment by segraef** [comment]
Thanks @tyconsulting, having a look at it.

**Comment by AlexanderSehr** [comment]
We're starting to pile them up. Thanks for all the great feedback @tyconsulting. @segraef, I guess right now everything is just waiting on the schema approval, right? I'd suggest to add this one in there as well, if you'd agree.

As an alternative we could however also re-use the private endpoint name logic, right? There's only ever one private link connection per private endpoint, so if we'd also be using the following it should also work (key vault example):
```bicep
name: privateEndpoint.?name ?? 'pep-${last(split(keyVault.id, '/'))}-${privateEndpoint.?service ?? 'vault'}-${index}'
```
Though instead of saying `privateEndpoint.?name` in the front, we could also use `privateEndpoint.?privateLinkServiceConnectionName` as per your suggestion.
That would be:
```bicep
name: privateEndpoint.?privateLinkServiceConnectionName ?? 'pep-${last(split(keyVault.id, '/'))}-${privateEndpoint.?service ?? 'vault'}-${index}'
```
and the same for the manual connection.

**Comment by segraef** [comment]
Implementation in progress, see linked PRs.
