### ISSUE TITLE
[AVM Module Issue]: resource name validation required to validate case

### ISSUE THREAD

**Issue by Brunoga-MS** [Azure/bicep-registry-modules#1050]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/storage/storage-account

### Description

Storage account resources do not allow for capital letters in the name. A validation or a note in the documentation to guide customers to use the right case is required.

**Comment by AlexanderSehr** [comment]
> ### Check for previous/existing GitHub issues
> * [x]  I have checked for previous/existing GitHub issues
> 
> ### Issue Type?
> Feature Request
> 
> ### Module Name
> avm/res/storage/storage-account
> 
> ### (Optional) Module Name if not listed above
> _No response_
> 
> ### (Optional) Module Version
> _No response_
> 
> ### Description
> Storage account resources do not allow for capital letters in the name. A validation or a note in the documentation to guide customers to use the right case is required.
> 
> ### (Optional) Correlation Id
> _No response_

ey @Brunoga-MS, thanks for the issue. I think a validation won't be possible because there is no `validate` function in Bicep like there is, for example, in Terraform. However, adding the guidance to the name parameter's metadata is a fair ask. @fblix  could you look into that and add it there or @Brunoga-MS ok course feel free to contribute if you want :)
