### ISSUE TITLE
[Feature Request]: Synapse Workspace: Missing `administrators` child module implementation - not possible to add EntraID Admin

### ISSUE THREAD

**Issue by Ralph101** [Azure/bicep-registry-modules#1071]
### Module path

/res/synapse/workspace

### Bicep version

0.1.0

### Describe the bug

It's not possbile to add a EntraID admin succesfully. We are missing the Administrator section equals to the sql/server module

### To reproduce

Run below code it will deploy a Synapse Workspace successfully but with a correct EntraID Admin

```bicep
resource synapseanalyticsAdministrator 'Microsoft.Synapse/workspaces/administrators@2021-06-01' = {
  name: 'name/activeDirectory'
  properties: {
    login: __sqlAdministratorLoginEntraId__
    sid: __initialWorkspaceAdminObjectId__
    tenantId: subscription().tenantId
  }
} 
```

When above code is added to the main.bicep file it works fine

### Code snippet

```Bicep
module synapseanalytics 'br/public:avm/res/synapse/workspace:0.1.0' = {
  name: '${deployment().name}-synapselink'
  params: {
    name: ''
    defaultDataLakeStorageAccountResourceId: storageaccount.id 
    defaultDataLakeStorageFilesystem: '' 
    sqlAdministratorLogin: __sqlAdministratorLogin__
    azureADOnlyAuthentication: true
    initialWorkspaceAdminObjectID: __initialWorkspaceAdminObjectId__
  }
}
```

**Comment by AlexanderSehr** [comment]
Hey @Ralph101,
thanks for raising this issue. It seems only the child-module must be added. This is less a bug, but a feature request - be it an absolutely reasonable one. Please note that the module is currently orphaned (i.e., it does not have an owner to maintain it), which means it falls to the smaller group of maintainers to triage issues and if need be update the module. It attached the 'feature request' label to the module for the time being. If one of the maintainers has capacity they will pick it up, though you're of course also invited to contribute if you want.
Once an internal owner is found, the issue would also automatically be assigned to that owner so that the person could take care of the issue right away.

**Comment by elanzel** [comment]
Hi @Ralph101, since there's no owner for this module, but i've contributed to migrate it, i'll try to support in best-effort for this issue.
