### ISSUE TITLE
[AVM Question/Feedback]: Passing parameters from PowerShell to Bicep

### ISSUE THREAD

**Issue by dmbuk** [Azure/bicep-registry-modules#1097]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello, I am trying AVM first time, and stumbled across the issue when passed param is ignored and resource name is autogenerated. 

Here is my deployment script:

```
# -------- Deploy ------------
$templateFile = 'cosmos.bicep'

$params = @{
    templateFile        = $templateFile
    name                = "$project-" + $templateFile
    ResourceGroupName   = $resourceGroup
    cosmosDbName        = "cosmos-$project-nprod-uks"
}


#Test the deployment
New-AzResourceGroupDeployment @params
```
and Bicep: 💪
```
param cosmosDbName string
param location string = resourceGroup().location
module cosmosDb 'br/public:storage/cosmos-db:3.0.2' = {
  name: cosmosDbName
  params: {
    backendApi: 'sql'
    cors: []
    createMode: 'Default'
    enableFreeTier: true
    isZoneRedundant: false
    location: location
  }
}
```
It deploys fine but the name supplied by cosmosDbName param is ignored, and I get **cosmos-hxzzok4a7msci** instead. 

What am I doing wrong? 😜🤦‍♂️

**Comment by krbar** [comment]
The immediate cause of your issue is that the name you're passing (in the line below the module) isn't the name of the Cosmos DB itself but rather the name of the deployment. The Cosmos DB account name should be provided within the params brackets. Since it wasn't specified, the module generated a default name.

Please also note that you're referencing a legacy, non-AVM module that doesn't adhere to the AVM specifications. Modules of this nature will eventually be phased out, as indicated in the [readme](https://github.com/Azure/bicep-registry-modules/blob/main/README.md). I highly recommend to use an AVM module as described below.

To utilize AVM modules effectively, ensure that the module path within the public registry follows the pattern: `br/public:avm/res/<resource-provider-name>/<resource-type>:<version>`. In your case, the path to the current version of the CosmosDB module is `br/public:avm/res/document-db/database-account:0.1.4`. This new, AVM-compatible module utilizes different parameters, which are documented [here](https://github.com/Azure/bicep-registry-modules/blob/avm/res/document-db/database-account/0.1.4/avm/res/document-db/database-account/README.md). Additionally, you can find code examples for various usage scenarios there.

Here is a modified example based on the bicep code you provided. Please note that this example may require some additional parameters, I just wanted to show you the correct placement of the `name` params within the code.

```bicep    
param cosmosDbName string
param location string = resourceGroup().location

module cosmosDb 'br/public:avm/res/document-db/database-account:0.1.4' = {
  name: '${uniqueString(deployment().name)}-cosmos-db' // name of the deployment
  params: {
    name: cosmosDbName // name of the Cosmos DB account
    location: location
    enableFreeTier: true
    locations: [
      {
        failoverPriority: 0
        isZoneRedundant: false
        locationName: location
      }
    ]
  }
}
```

**Comment by dmbuk** [comment]
Wow, thank you @krbar  Kris for the thorough answer. I've made a silly mistake )))

I tried to follow you suggestion to use the latest module and immediately hit two issues:
1. Difficult to locate a required module. I wanted to deploy CosmosDb
2. Impossible to guess or use IntelliSense for some complex parameters like [locations]

See my pain here:

https://github.com/Azure/bicep-registry-modules/assets/70722860/99d0d633-d694-41c5-971b-77de682d6b33



I've listened to Al-Ctrl-Azure  podcast with @jtracey93 recently, looks like we are having that "many modules, not sure which to use" issue again?

**Comment by dmbuk** [comment]
Furthermore, I am not clear how to deploy a SQl API. It creates Mongo Db by default, I can't see a parameter to change it. 
Please advise @krbar

**Comment by krbar** [comment]
> 1. Difficult to locate a required module. I wanted to deploy CosmosDb

The list of all modules can be found [here](https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-resource-modules/).
As mentioned in the previous comment, you should know the resource provider and the name of the resource type, then use the naming pattern provided above. There are several way to find out the provider name, see the [documentation](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-services-resource-providers).

> 2. Impossible to guess or use IntelliSense for some complex parameters like [locations]

Although we strive to offer IntelliSense where possible, we have not yet covered all parameters. If no IntelliSense is available, you can refer to the usage examples in the module documentation. BTW, you can easily jump to the documentation by hoovering your mouse over the module name in VSCode:

<img width="529" alt="image" src="https://github.com/Azure/bicep-registry-modules/assets/20225789/f7516441-b56f-4392-85c4-e61363a3cdf2">

**Comment by krbar** [comment]
> Furthermore, I am not clear how to deploy a SQl API. It creates Mongo Db by default, I can't see a parameter to change it. Please advise @krbar

See module [usage example 5](https://github.com/Azure/bicep-registry-modules/blob/avm/res/document-db/database-account/0.1.4/avm/res/document-db/database-account/README.md#example-5-sql-database). I don't know this module in depth, but I think the parameter `sqlDatabases` must be provieded.

<img width="649" alt="image" src="https://github.com/Azure/bicep-registry-modules/assets/20225789/d64e1080-d116-4077-ba71-c3710a388d0d">

**Comment by krbar** [comment]
@dmbuk Please let me know if it helped and if the issue can be closed. Thanks!

**Comment by dmbuk** [comment]
hi @krbar , thanks for the explanantion. 
I will follow your advice, feel free to close the issue👍
