### ISSUE TITLE
[Module Proposal]: DAPR Container Apps Environment

### ISSUE THREAD

**Issue by Gordonby** [Azure/bicep-registry-modules#118]
### Have you checked this module does not already exist in the registry?

Yes

### Why is the module needed?

Stamping out Container Apps and Container Apps Environments requires lots of repetition. 
In the case of DAPR, there are common patterns for the DAPR components that are created in the Container Apps Environment.

These common patterns can be enabled in the module by way of parameters for 
- Service bus
- Cosmos
- Blob

Container App Environments also have dependencies on other resources which can be optionally created in the template.

### Module path

app/dapr-containerapps-environment

### Describe the module

A module that creates the Container App environment with smart defaults for private networking, a log analytics workspace, container registry resources and the relevant DAPR components and configuration. It could also include the creation of the other azure resources but perhaps just passing the resources in by reference would be more suitable.

**Comment by greenie-msft** [comment]
+1 to this proposal. 

This proposal has support from the Dapr project. It simplifies the creation of container app environments and Dapr components.

**Comment by alex-frankel** [comment]
Approved - I like the idea of starting the `app` directory!

**Comment by paulyuk** [comment]
Starting with an app and some "building blocks" like the messaging brokers and data stores will be very helpful.  I just wrote an implementation of a template that was near 2000 lines of bicep with lots of repetition.  See end of this.

In addition to what Nick says, to get the most benefit out of your resources you want to configure them with monitoring, securing and pipeline resources, e.g.
- Log Analytics workspace
- App Insights
- Keyvault
- Azure Container Registry

These introduce a number of interdependencies that must be configured.  The container registry is particularly tricky because it needs to exist before you can build/tag/push the image, and then your containers must pull with pull secrets from it.  

Here's a reference example that uses `azd` + an \infra folder to deploy an app:
https://github.com/Azure-Samples/pubsub-dapr-csharp-servicebus

@alex-frankel  fyi
