### ISSUE TITLE
[AVM Module Issue]: avm/res/network/virtual-network duplicate subnet creations

### ISSUE THREAD

**Issue by rodney-almeida** [Azure/bicep-registry-modules#1519]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### Module Name

avm/res/network/virtual-network

### (Optional) Module Version

0.1.5

### Description

I have used this module a few times and most of the times i don't have an issue with it and creating subnets. However, I have had to clone it and modify it locally for a particular project as I kept getting "Another operation on this or dependent resource is in progress" when creating the subnets (child module call).
I removed the child module call on the local version because (as the commented section in the bicep mentions) the subnets are already been done in the parent vnet resource.
I have seen the commented section and question is, is the child subnet module call suppose to be included in the module that is been referenced publicly or was that an oversight? In other words, is there a way you can test the subnet module without then having this duplicate call included in the public referenced module?
If it is to stay and therefore duplicate the subnet creation, can we have a batch decorator to help prevent these error messages?

PS: love using these module, great work to all the team helping to create and maintain them :)

### (Optional) Correlation Id

a8b70743-ceff-41e0-933e-0bdd2c1a05be

**Comment by elbatane** [comment]
Hi, thank you @rodney-almeida for raising the issue. We will review it and come back to you.

**Comment by AlexanderSehr** [comment]
Hey @rodney-almeida,
thanks for raising the issue. To provide some context
- You're right that the subnet deployment is in the resource effectively twice, once in the properties of the vnet, once as a seperate resource
- The first (property) MUST be there, as without, the vnet deployment would first delete all current subnets, and then re-deploythem via the child-module. So that's not an option
- The first (child-module) should be there for 2 reasons
  - It would in theory be published as its own module (something that happens via the CARML CI, just not in AVM yet)
  - It has more features, like RBAC that you cannot deploy via the property (though could create custom logic for to make it deployable in the parent).

Now to your problem - if you get the issue that 'another operation is in progress' it sounds like there is a concurrency issue. @elbatane let's try to reproduce the issue, but I guess, like suggested by @rodney-almeida, we may need a `batchSize(1)` annotation for the child-module deployment.

**Comment by elbatane** [comment]
Hi  @rodney-almeida , did you have teh chance to test the solution from @AlexanderSehr ? Thanks!

**Comment by h2floh** [comment]
+1 ⬆️  I ran and run into the same issue. First deployment is always good and on the second run if resources already exist then I see this error hit often, like 90% + almost not possible to test out new changes without deleting the network and associated resources. Since virtualNetwork is a module I can't use the `batchSize` decorator as a workaround or to try it out.

**Comment by AlexanderSehr** [comment]
Fair.

 @elbatane, I guess to be on the safe side, let's add the batch size deployment. The issue does not seem to happen consistently, but if it happens, I guess it's reason enough.

**Comment by rodney-almeida** [comment]
@elbatane @AlexanderSehr 
I have create a PR for this. Please let me know if there is anything i have missed.
Thanks
