### ISSUE TITLE
[AVM Feedback]: Can we make sure types are defined and used in a consistent manner?

### ISSUE THREAD

**Issue by brazarb** [Azure/bicep-registry-modules#1525]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I've noticed here the `service` is a required parameter, where in other resources it's optional

Storage Account:
https://github.com/Azure/bicep-registry-modules/blob/19c2f75a2d292e60b33997be92899a413c3a89a7/avm/res/storage/storage-account/main.bicep#L714

https://github.com/Azure/bicep-registry-modules/blob/c3883b4b169356df6d7d2818f513c4d00fc6ad0b/avm/res/storage/storage-account/main.bicep#L481-L494

---

Key Vault:
https://github.com/Azure/bicep-registry-modules/blob/c3883b4b169356df6d7d2818f513c4d00fc6ad0b/avm/res/key-vault/vault/main.bicep#L392

https://github.com/Azure/bicep-registry-modules/blob/c3883b4b169356df6d7d2818f513c4d00fc6ad0b/avm/res/key-vault/vault/main.bicep#L249-L260

**Comment by matebarabas** [comment]
Hi @brazarb, thank you for opening this issue. Just a quick clarifying question: are these two just examples or have you observed this in other modules too? If the latter, can you please point to those modules too? Thank you!

@Azure/avm-core-team-technical-bicep, if this difference in implementation is intentional, can you please explain the logic; if it's not can you please determine which approach should be followed (service being a mandatory or optional parameter), so we can ask module owners to update their code? Thank you!

**Comment by AlexanderSehr** [comment]
Hey @brazarb,
the logic is implemented as per the corresponding [AVM specification](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#private-endpoints). In general, the idea is to always provide a default (i.e., make the parameter optional) if only one `groupId`/`service` is available (while still being able to overwrite it), while any resource where more than one  `groupId`/`service` requests the user to specify it as we would likely make a mistake when assuming a value on the user's behalf.

The example you provided is a good one as the Storage Account accepts values like `blob`, `files`, etc., while for the Key Vault only accepts `vault` and nothing else.

**Comment by AlexanderSehr** [comment]
Hey @brazarb,
did my explanation clarify the reasoning for the current implementation / made sense?
If so, we could go ahead and close the issue :)
