### ISSUE TITLE
[AVM Module Issue]: cognitive-services/account deployments not recognized

### ISSUE THREAD

**Issue by tonyskidmore** [Azure/bicep-registry-modules#1693]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/cognitive-services/account

### (Optional) Module Version

0.5.1

### Description

The `deployments` parameter is not recognized in vscode intellisense or when running the module.

As per [Using deployments in parameter set](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cognitive-services/account/README.md#example-1-using-deployments-in-parameter-set):

```
module account 'br/public:avm/res/cognitive-services/account:0.5.1' = {
  name: 'accountDeployment'
  params: {
    // Required parameters
    kind: 'AIServices'
    name: 'csad002'
    // Non-required parameters
    customSubDomainName: 'xcsadai'
    deployments: [
      {
        model: {
          format: 'OpenAI'
          name: 'gpt-35-turbo'
          version: '0301'
        }
        name: 'gpt-35-turbo'
        sku: {
          capacity: 10
          name: 'Standard'
        }
      }
    ]
    location: 'uksouth'
  }
}
```
Results in:
```
Error BCP037: The property "deployments" is not allowed on objects of type "params". Permissible properties include "allowedFqdnList", "apiProperties", "customerManagedKey", "customSubDomainName", "disableLocalAuth", "dynamicThrottlingEnabled", "enableTelemetry", "lock", "managedIdentities", "migrationToken", "networkAcls", "restore", "restrictOutboundNetworkAccess", "roleAssignments", "tags", "userOwnedStorage".
```

#1466

**Comment by ilhaan** [comment]
@tonyskidmore thanks for submitting an issue about this. The problem here is that the changes made in https://github.com/Azure/bicep-registry-modules/pull/1466 have not been published yet since there is a pipeline issue at the moment: https://github.com/Azure/bicep-registry-modules/actions/runs/8718612264. 

The pipeline issue is being discussed in https://github.com/Azure/bicep-registry-modules/pull/1466 (all the way at the bottom). Once that has been resolved the publishing step should be able to run and you'll be able to use the `deployments` parameter as intended. 

CC: @jceval, @AlexanderSehr, @matebarabas

**Comment by mortenvpschmidt** [comment]
Any updates on this issue?  We need 'deployments' to our Cognitive service  😄

**Comment by ilhaan** [comment]
@mortenvpschmidt The publishing of the module went through 3 days ago and you should be able to use it now. See this for more info: https://github.com/Azure/bicep-registry-modules/pull/1466#issuecomment-2092617118
