### ISSUE TITLE
[AVM Question/Feedback]: Just wondering if anyone else would find it beneficial to have the allowed role definitions defined within the type definition for each module?

### ISSUE THREAD

**Issue by brazarb** [Azure/bicep-registry-modules#1741]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Container Registry
![image](https://github.com/Azure/bicep-registry-modules/assets/111027880/a0744ebc-0c63-4b1d-b19c-f8789a885290)

![image](https://github.com/Azure/bicep-registry-modules/assets/111027880/9bd9a45f-44a0-42ce-ba1d-546a625f9f66)

![image](https://github.com/Azure/bicep-registry-modules/assets/111027880/8f1da105-552e-4732-a42f-5385f96e5623)

**Comment by matebarabas** [comment]
@JPEasier, this issue seems to be related to the Container Registry module. Can you please have a look? Thanks!

**Comment by AlexanderSehr** [comment]
Hey @brazarb, thanks for bringing this up. @matebarabas this is a general suggestion, and is not Container Registry-specific.

That being said, @brazarb, we did test a few things and also participated in a related conversation in the Bicep repository: https://github.com/Azure/bicep/issues/1895

Ideally, we would not need to specify any roles in the modules if there were a function to get the GUIDs for the roles for us. However, as this function does not exist (and as there is no viable workaround), the next best solution was to add a subset of resource-relevant roles into the templates themselves (which you can always find in the `builtInRoleNames` variable).

What you'd suggesting builds on top of this as right now a user would need to know the names of the roles in order to use them. There is a long running draft PR open in which I created a [PoC](https://github.com/Azure/bicep-registry-modules/pull/706) to extract the roles and at least add them to the readme's. But I didn't have time to finish it.

Your solution would be more elegant but unfortunately has a big catch which I believe will prevent us from implementing it. As soon as we add an 'allowedSet' to the parameter to enable users to pick from a list of role names, you lock the user out from any role that isn't specified both in that set, and the `builtInRoleNames` variable. As the later explicitely does not contain all possible roles for the given scope (as this would massively increase the size of the template), we'd lock users out of most roles they could assign to the given resource.

Right now, we instead support the following 3 options
```
        {
          roleDefinitionIdOrName: 'Owner' // <== Must be known
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
        {
          roleDefinitionIdOrName: 'b24988ac-6180-42a0-ab88-20f7382dd24c' // <== Must be looked up 
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
        {
          roleDefinitionIdOrName: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'acdd72a7-3385-48ef-bd42-f606fba81ae7') // <== Must also be looked up. Just the full syntax of option 2
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
```

I hope that explanation maxes sense.
