### ISSUE TITLE
[AVM Module Issue]: cdn/profile/afdEndpoint needs hostName output.

### ISSUE THREAD

**Issue by russellds** [Azure/bicep-registry-modules#1785]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cdn/profile

### (Optional) Module Version

0.1

### Description

The `afdEndpoint` module should output `afdEndpoint.properties.hostName` so that DNS entries can be created in the same bicep deployment that the `afdEndpoint` is being deployed in.

**Comment by gbeaud** [comment]
Thanks for sharing this feature request, I'll add this output in the next release 👍

**Comment by gbeaud** [comment]
You're talking about the hostName contained in the customDomain tied to a route in an afdEndpoint, right? We are changing the module to support multiple custom domains so you would likely get an array of host names - please let me know if this is ok for you 👍

**Comment by russellds** [comment]
That works for me, it makes sense that If it supports an array as input, it would return array of hostNames as output.

**Comment by gbeaud** [comment]
[@russ](https://github.com/russellds) Sorry for the late reply; is that fine for you if the afdEndpoint module outputs the list of routes it contains? Routes then contain a list of customDomains which have the hostName property you're looking for.

I'm asking because we can't make a double nested for loop to iterate over all routes and then iterate over all customDomains to output an array of hostNames directly due to Bicep limitations: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/loops#loop-limits

So I would basically add this to afdEndpoint/main.bicep:
```
@description('The list of routes for the AFD Endpoint.')
output routes array = routes ?? []
```

Other options would be to create an intermediate variable or to use a lambda function but I'd like to avoid going in that direction to keep the code cleaner - so please let me know if you're okay receiving an array of routes (which ultimately contain the hostNames) 👍

**Comment by russellds** [comment]
As long as the array of routes have a property that contains the custom host name, I am good.
