### ISSUE TITLE
[AVM Module Issue]: Data Factory module should support tenantId parameter in git configuration

### ISSUE THREAD

**Issue by MarkFarkas** [Azure/bicep-registry-modules#1907]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/data-factory/factory

### Description

It's not possible to use an Azure DevOps organization that's in a different Entra ID tenant from the Data Factory for git integration.
A new parameter, gitTenantId should be defined that allows specifying the tenant ID for the Azure DevOps organization.
Default value could be the tenant ID of the current deployment scope.
The value can then be used in the optional tenantId property of the FactoryVstsConfiguration object:
https://learn.microsoft.com/en-us/azure/templates/microsoft.datafactory/factories?pivots=deployment-language-bicep#factoryvstsconfiguration

**Comment by clintgrove** [comment]
I have reached out to our product group. I will await to now hear back from them. Give this a week please. Thank you

**Comment by Kathedra** [comment]
I just want to add my experience to the issue @MarkFarkas addresses here, because I have had a (vaguely) similar issue before with Synapse workspace deployment (see #1679 ).

**In my experience, there are a few different issues:**
1 the current parameter set do not provide full control of setting the repo config: the tenantId and lastCommitId parameters are missing. when not provided, it just randomly redirects to an MFA login (i am a guest user on multiple organizations) whenever trying to open the data factory studio.
2 using the default settings of the template (leaving out the repository config), the manually configured repository config is overwritten (thus, the config is removed, and you have to reconfigure the repo config after each data factory infrastructure deployment)
3 (suggestion) the parameter set should be a user defined (object) type and the gitConfigureLater parameter should be removed. 

Adding to the suggestion, currently, this is how I have the git related parameters configured. This is based on the same structure as Synapse workspace repoconfig in the AVM. (for your information: I create a module on top of the AVM which uses a user defined type to provide values for the git related parameters):
```gitConfigureLater: empty(repoConfiguration) ? true : false
    gitAccountName: repoConfiguration.?accountName
    gitProjectName: repoConfiguration.?projectName
    gitRootFolder: empty(any(repoConfiguration.?rootFolder)) ? '/ADF': repoConfiguration.?rootFolder
    gitRepositoryName: empty(any(repoConfiguration.?repositoryName)) ? 'ADF' : repoConfiguration.?repositoryName
    gitCollaborationBranch: empty(any(repoConfiguration.?collaborationBranch)) ? 'development' : repoConfiguration.?collaborationBranch
    gitRepoType: empty(any(repoConfiguration.?type)) ? 'FactoryVSTSConfiguration' : repoConfiguration.?type```

**Comment by MarkFarkas** [comment]
I agree with Kathedra about providing more control over the git configuration of the workspace.
Because this issue was blocking me (and because the AVM module overwrites the git configuration when the parameter is not provided), I created the following module that I deploy after the AVM module deployment as a workaround:
```targetScope = 'resourceGroup'

param adfName string
param gitAccountName string
param gitProjectName string
param gitBranchName string
param gitDisablePublish bool
param gitRepositoryName string
param gitRootFolder string
param gitTenantId string
param resourceTags object
param resourceLocation string = resourceGroup().location


resource adfGitConfig 'Microsoft.DataFactory/factories@2018-06-01' = {
  name: adfName
  tags: resourceTags
  location: resourceLocation
  properties:{
    repoConfiguration: {
      type: 'FactoryVSTSConfiguration'
      accountName: gitAccountName
      projectName: gitProjectName
      repositoryName: gitRepositoryName
      collaborationBranch: gitBranchName
      disablePublish: gitDisablePublish
      rootFolder: gitRootFolder
      tenantId: gitTenantId
    }
  }
}

```

I'm using this module because I really wanted to avoid forking the AVM repo or creating a custom module myself.

**Comment by MarkFarkas** [comment]
@Kathedra , I was actually not aware of the importance of the lastCommitId parameter. My workspace has publishing from ADF Studio disabled and this parameter is not used for anything else as far as I am aware.
I'm using an Azure DevOps pipeline to redeploy the workspace when a change is made to the template so if I had to use the parameter, I would run an Az Powershell task to retrieve the current value from the workspace and provide the value to the bicep template.

**Comment by clintgrove** [comment]
Hey guys. I am looking to add lastCommitID to the parameters. I will add this fix soon. This may go some way in helping.

**Comment by Kathedra** [comment]
personally I prefer a solution that also gives us the ability to manually configure the repository settings, as mentioned in my 2nd issue. This way, Bicep does not handle the config and doesn't overwrite it. Any quick fixes for that @clintgrove?
