### ISSUE TITLE
Azure Firewall & IP Prefix

### ISSUE THREAD

**Issue by aidanfinn** [Azure/bicep-registry-modules#2087]
There appears to be a limitation with the Azure Firewall module. It is limited to using a single IP address. We should be able to supply an IP Prefix resource ID, number of IP's to create, a name foundation, and a subnet ID.

**Comment by cloudchristoph** [comment]
Hi @aidanfinn,

## Public IP Prefixes
Public IP Prefixes are already available.

From the examples:

```bicep
module azureFirewall 'br/public:avm/res/network/azure-firewall:<version>' = {
  name: 'azureFirewallDeployment'
  params: {
    // Required parameters
    name: 'nafpip001'
    // Non-required parameters
    azureSkuTier: 'Basic'
    location: '<location>'
    managementIPAddressObject: {
      managementIPAllocationMethod: 'Static'
      managementIPPrefixResourceId: '<managementIPPrefixResourceId>'
      name: 'managementIP01'
      skuName: 'Standard'
      skuTier: 'Regional'
    }
    publicIPAddressObject: {
      name: 'publicIP01'
      publicIPAllocationMethod: 'Static'
      publicIPPrefixResourceId: '<publicIPPrefixResourceId>'
      skuName: 'Standard'
      skuTier: 'Regional'
    }
    virtualNetworkResourceId: '<virtualNetworkResourceId>'
    zones: []
  }
}
```
## Number of Public IPs created from a Prefix
This is missing.
Maybe worth a PR: Number of Public IP addresses to be created from the prefix, if provided.

## Name Foundation
Doesn't seem to be an issue, or is deliberately bypassed. See comment on the Community Call by @jtracey93: https://youtu.be/LprWndLjLH0?si=p2F_O3aF_K1d2Fkr&t=3039. Will possibly come with the new “utilities” category of modules.

## Subnet ID
What do you need here? From my understanding, a Virtual Network Resource ID is expected. This is because the subnets must be named accordingly “AzureFirewallSubnet” and (optionally) “AzureFirewallManagementSubnet”. The subnets are therefore derived from the VNET resource ID. Am I missing something?

---

I hope some of the information here helps you. Because - as we all know from your **great** blog (yes, I'm a reader and fan!) - you've been slowed down by modules like this in the past. 

Best,
Christoph

**Comment by AlexanderSehr** [comment]
Hey @hundredacres, please take a look when you can :)

**Comment by hundredacres** [comment]
As @cloudchristoph states @aidanfinn, you can pass an IP Prefix resourceID to the Firewall module, but the user would need to create the prefix beforehand as a dependency. The firewall module doesn't create the objects itself.

Here's an example using the available IP Prefix module:

```
module publicIpPrefix 'br/public:avm/res/network/public-ip-prefix:<version>' = {
  name: 'publicIpPrefixDeployment'
  params: {
    // Required parameters
    name: 'npipmax001'
    prefixLength: 28
    // Non-required parameters
    location: '<location>'
    zones: []
  }
}
```

Here's how the resource is created in the tests:

```resource publicIPPrefix 'Microsoft.Network/publicIPPrefixes@2023-11-01' = {
  name: publicIPPrefixName
  location: location
  sku: {
    name: 'Standard'
    tier: 'Regional'
  }
  properties: {
    prefixLength: 30
    publicIPAddressVersion: 'IPv4'
  }
  zones: []
}
```

And then you just grab the outputs of either the module or resource in your Azure Firewall config.
