### ISSUE TITLE
[AVM Question/Feedback]: Duplicate security rules in avm.res.network.network-security-group

### ISSUE THREAD

**Issue by corey-stidston** [Azure/bicep-registry-modules#2185]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello, I have started to use AVM recently and experienced server timeouts when attempting to deploy NSG rules using the NSG module. According to Microsoft support, this was caused by the ARM and Network Resource provider resources being out of sync, I'm still having these issues even after resources have been synced, so the root cause is still unknown and investigation still in progress.

On closer inspection of the network security group, I could see that security rules are being created twice. Once on [L:74 ](https://github.com/Azure/bicep-registry-modules/blob/c3f9b321118d0809ab5fb66f5552e31cd54d3c01/avm/res/network/network-security-group/main.bicep#L74C5-L74C18) of the network-security-group module and a second time on [L:122](https://github.com/Azure/bicep-registry-modules/blob/c3f9b321118d0809ab5fb66f5552e31cd54d3c01/avm/res/network/network-security-group/main.bicep#L122) using a security-rule module.

I'm keen to understand why it was implemented this way as it seems redundant and I'm wondering if that's causing the resources to be out-of-sync. Cheers

**Comment by ChrisSidebotham** [comment]
Hi @corey-stidston - Your issue looks to be correct - @ahmadabdalla can you take a look into this?

**Comment by ahmadabdalla** [comment]
Thanks @corey-stidston for raising this. Your issue is on point. There is currently a limitation where if we pass in an empty payload to the `securityRules` property, it will empty the NSG from the existing security rules, which will then be redeployed individually via the child module for loop. This is not a desired outcome as this will impact network traffic if the rules are removed and then added. 

However, from a module perspective, the only way for us to test the child module `security-rule` is by passing it from the parent, and this was an approach we've undertaken in the past before AVM and had a comment for customers to remove the child module deployment when they take the source code into their environment. 

@Azure/avm-core-team-technical-bicep Currently the only option to solve this is by not deploying the child module alongside the parent, which then prevents us from testing the child. So, we either take out the child module from the library and just have the parent or keep the child and remove the tests. Any inputs on this please?

CC: @AlexanderSehr @eriqua @jtracey93

**Comment by AlexanderSehr** [comment]
Hey @ahmadabdalla, well described. 😄 

So, yes - we do have the child, because historically speaking in CARML we've also been publishing the child-modules, and intention-wise we want to do the same in AVM, once we can technically do that. This is also why all child modules follow the same conventions as the parent modules.
But some modules, like this one, VNET, RouteTable etc. are special in that they have both a property for their child as well as the child itself. And because all of them really really like to delete these child-resources if you don't provide them at every place, we have use the property. The child-module in that sense is only also invoked to be able to test it, as @ahmadabdalla already described. If we were not to pass values through, we'd run the risk of heaving dead/non-working code that we don't know about.

I have the hope that the other PGs will follow the changes the VNET team is currently implementing, that is to not auto-delete child-resources, which would enable us to remove the property from the parent without any issues. But that's currently only wishful thinking.

At least NSG is in a slightly better position as the child-module, as well as the property have the same parameters. In case of e.g., the VNET, the subnet-child module has actually additional features like RBAC that you cannot set in the parent property. Ah well...

Anyways - deploying the child-module 'should' not be a problem. But the same was said about the VNET module and we ended up adding a `batchSize(1)` to the child-module deployment because of concurrency issues. Maybe this would help here as well with the issue at hand?

If bad comes to worse, we could remove the child. It's just that looking into the future with us wanting 'complete' modules & publish child-modules, we'd need to undo the removal effectively.

**Comment by ahmadabdalla** [comment]
@AlexanderSehr I will be removing the child module `securityRules` at this stage. And we can bring it back if there is a customer need for it. Seeing this at multiple customers so far doesn't provide the value it is intended for and causing confusion given the current limitation on the provider side.
