### ISSUE TITLE
[AVM Module Issue]: avm/res/web/serverfarm missing sku section

### ISSUE THREAD

**Issue by Ralph101** [Azure/bicep-registry-modules#2188]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/web/serverfarm

### Description

```bicep
module serverfarm 'br/public:avm/res/web/serverfarm:0.1.1' = {
  name: 'serverfarmDeployment'
  params: {
    // Required parameters
    name: 'wsfmin001'
    skuCapacity: 2
    skuName: 'S1'
    // Non-required parameters
    location: __location__
  }
  scope: resourceGroup(rgName)
  dependsOn: [
    rg
  ]
}
```
This section cannot be run because skuName and skuCapacity is not a valid is expected the sku section

**Comment by tsc-buddy** [comment]
@Ralph101 thanks for submitting this - Theres an exisiting issue open for this. The problem is due to environment issues on our end not allowing the recent module version with SKU improvements to be published. I'll leave this open for now and will close once we get our fixes into the AVM environment for publishing.
