### ISSUE TITLE
[AVM Module Issue]: VMSS unable to deploy empty (no VM template)

### ISSUE THREAD

**Issue by danycontre** [Azure/bicep-registry-modules#2315]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/compute/virtual-machine-scale-set

### (Optional) Module Version

0.2

### Description

Have been trying to deploy a VMSS with flexible orchestration without any VM template, but the module is enforcing the creation of the VM template therefore expecting all the associated parameters. In the meantime, we are using a custom module with the following definition:
resource vmssFlex 'Microsoft.Compute/virtualMachineScaleSets@2024-03-01' = [for i in range(1, count): {
    location: location
    name: '${namePrefix}-${padLeft(i, 3, '0')}'
    zones: useAvailabilityZones ? [
        '1'
        '2'
        '3'
    ]: null
    properties: {
        orchestrationMode: 'Flexible'
        zoneBalance: useAvailabilityZones ? true: false
        platformFaultDomainCount: useAvailabilityZones ? 1: platformFaultDomainCount
    }
    tags: tags
}]

**Comment by rahalan** [comment]
@danycontre thanks for bringing that up. I will look into it

**Comment by rahalan** [comment]
@danycontre May I ask what you want to achieve with an literally empty VMSS? Please elaborate. If the module would support such a scenario, massive rework is needed and the code will be getting hard to read.

**Comment by danycontre** [comment]
@rahalan we are using VMSS flexible orchestration, we create it empty just with FD and AZ settings and then deploy VMs and associate them with the VMSS Flex, this will be used for AVD LZA and Epic as replacement of availability sets and to manage AZ distribution.

**Comment by rahalan** [comment]
@danycontre I am reluctant to implement this. It feels like a very special edge case, that can easily covered with the code you provided as a sample. On the other hand, implementing this would mean a lot of rework for the module and many parameters which are now required need to be optional, making it harder to understand for the typical module user. Plus there seems to be a Bicep limitation, that I can't have for loops inside of optional parameters (because I will have a if loop on the top). I will discuss with the AVM core team and see what the team makes out of it. I'll keep you posted.

**Comment by rahalan** [comment]
@danycontre it looks like a lot of rework of the VMSS to achieve that. Currently I don't have the capacity to do that. For now I have to decline this issue. Feel free to make a PR yourself. Cheers, Rainer

**Comment by danycontre** [comment]
Thanks for the insights @rahalan 

cc: @mbilalamjad
