### ISSUE TITLE
[Bug Report]: AppGateway Request and Response buffers default in module

### ISSUE THREAD

**Issue by ramuvr** [Azure/bicep-registry-modules#2404]
### Describe the bug

As per [MS Doc](https://learn.microsoft.com/en-us/azure/application-gateway/proxy-buffers), the value for buffers  should default to true.

"By default, both Request and Response buffers are enabled on your Application Gateway resource but you can choose to configure them separately."

### To reproduce

Access file modules\network\application-gateway\main.bicep and see code snippet values

### Code snippet

```Bicep
@description('Optional. Enable request buffering.')
param enableRequestBuffering bool = false

@description('Optional. Enable response buffering.')
param enableResponseBuffering bool = false
```

**Comment by AlexanderSehr** [comment]
Hey @ilhaan,
I just migrated this issue over from CARML. Please take a look and triage if still relevant :)

**Comment by ilhaan** [comment]
@AlexanderSehr I will take a look

**Comment by AlexanderSehr** [comment]
Hey @ilhaan, please triage the issue when you get the chance :)

**Comment by ilhaan** [comment]
@AlexanderSehr So the [MS doc](https://learn.microsoft.com/en-us/azure/application-gateway/proxy-buffers) linked in the original issue by @ramuvr does say that request and response buffers are enabled by default. However, it also does say this: 
> You can keep either the Request or Response buffer, enabled or disable, based on your requirements and/or the observed performance of the client systems that communicate with your Application Gateway.
> Warning
> We strongly recommend that you test and evaluate the performance before rolling this out on the production gateways.

The change to make these default to `true` is simple, but I am concerned about the impact it can have on users of the module who are using the current default of `false` when they upgrade to a new published version after we this update. 

I see us having two options in this situation: 
1. Remove the default `false` and force users to explicitly define a value for this so they are aware and can make a decision on their own.
2. Change major version so that users know there is a major change to a config. Not sure how we've been handling these in AVM and a quick search through AVM docs does bring up info on versioning for upgrades like this. 

Please let me know your thoughts @AlexanderSehr

**Comment by AlexanderSehr** [comment]
Hey @ilhaan,
thanks for the research. Regarding the versioning we'd go with semver - if - we're already on 1.0. However, as we're not, breaking changes are treated as 'minor' version updates. So we'd update the `version.json` from let's say `0.2` to `0.3`.

To the topic at hand - if they're enabled by default then I'm inclined to recommend setting them to enabled as well. But I can't say that I know the service well enough to judge the implications. Ultimately, it would be up to you.
Mind you, this is just an issue we carried over from CARML to finally get around and properly triage it. If in doubt, you're more than welcome to close it as 'not planned' with the reasoning you've given above. No pressure 💪

**Comment by ilhaan** [comment]
@AlexanderSehr Sounds good. Thank you!
