### ISSUE TITLE
[AVM Module Issue]: DBforPostgreSQL Flexible Servers Private Endpoints

### ISSUE THREAD

**Issue by sam-bryant** [Azure/bicep-registry-modules#2578]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/db-for-postgre-sql/flexible-server

### Description

This module does not appear to have the privateEndpoints parameter found in other modules.  I apologize if I'm missing something.

**Comment by donheerschap** [comment]
@josearper I made a draft https://github.com/Azure/bicep-registry-modules/pull/2613 which contains changes that would fix this issue. The pipeline fails because of subscriptions limits after a few deployments. Besides PSrule failed on defaults e2e tests on settings which shouldn't be in the defaults IMHO, but I added them (for ex. highAvailability) to let validation pass.

@sam-bryant Out of curiosity why not "just" use private mode with a delegated subnet?

**Comment by sam-bryant** [comment]
@donheerschap - I think you are right that I should just be using that.  This a new resource for us and I was hacking at it manually via the portal and noticed the private endpoint options and couldn't translate that into the module definition.  I think I crossed some wires that led me down this route.

**Comment by AlexanderSehr** [comment]
Hey @josearper, could you please take a look and triage the issue at your earliest convenience? 💪

**Comment by sam-bryant** [comment]
As far as I'm concerned you could probably disregard this.  At the moment we are paused on our direction with this and might be going a different direction altogether.

I apologize for any inconveniences.  Thank you for the analysis so far.
