### ISSUE TITLE
New directory under storage account container

### ISSUE THREAD

**Issue by gerrynicol** [Azure/bicep-registry-modules#2579]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/storage/storage-account

### Description

Looking to see if there could be a change made to the storage module to allow the creation of directory's under a container

**Comment by jtracey93** [comment]
Hey @ktremain,

As per the definition of a utility module [here](https://azure.github.io/Azure-Verified-Modules/specs/shared/module-classifications/#:~:text=WAF%20best%20practices.-,Utility%20Module,-(draft%2C%0Asee) this does not fit the purpose of a utility module, IMHO.

I would say if this cannot be done from the control plane side of things for the storage account module and is a data plane action, a deployment script could be used, but id just suggest calling that as a separate module call instead with the already published options for deployment scripts.

**Comment by AlexanderSehr** [comment]
I guess there is some wiggle room if we'd consider data plane operations not as the 'deployment of Azure resources' but it would be an implementation for a very specific use case, that is, to create folders without any content. I'm not sure if we'd want to go there 💭 
If we were, I'd wander what else would make sense for such a script to do. Setting ACLs would probably make sense? 

The challenge will eventually be that custom code is imperative instead of declarative which is what IaC wants to be. Naturally, utility modules are a prime candidate for imperative code - but where should you draw the line? Should you draw a line?

Happy to discuss this further :)

**Comment by ktremain** [comment]
@gerrynicol As per the other conversations here, this feature request doesn't fit into the existing Storage Account Resource Module, and would have to be done as a separate script/deployment.

**Comment by gerrynicol** [comment]
Hi there, I know this is closed, but would you be able to provide any examples of guidance on how this could be done. i.e. if the storage account is deployed using the AVM using private endpoints, is there then the ability to create a directory structure under a container? Found very little online about this. Thanks
