### ISSUE TITLE
[AVM Module Issue]: avm/ptn/security/security-center -  ASC Default policy initiative onboarding

### ISSUE THREAD

**Issue by jikuja** [Azure/bicep-registry-modules#2664]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/ptn/security/security-center

### Description

#[ ASC Default policy initiative ](https://www.azadvertizer.net/azpolicyinitiativesadvertizer/1f3afdf9-d0c9-4c3d-847f-89da613e70a8.html) onboarding

In my opinion this is nice addition for this pattern. Allowing to enable any existing security policy with parameters would be nice.

**Comment by tony-box** [comment]
@jikuja this request for policy assignments looks like it would fall under the purview of the https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/policy-assignment module. You can use that pattern to deploy any/all of the built in azure policies.

I am going to close this since it's not in scope of the security-center pattern

**Comment by jikuja** [comment]
> @jikuja this request for policy assignments looks like it would fall under the purview of the https://github.com/Azure/bicep-registry-modules/tree/main/avm/ptn/authorization/policy-assignment module. You can use that pattern to deploy any/all of the built in azure policies.

True

> I am going to close this since it's not in scope of the security-center pattern

Should this module documentation include a recommendation/hint to deploy ASC policy initiative assignment with ptn/authorization/policy-assignment instead of relying on Defender's background processes
