### ISSUE TITLE
ALZ: Need to add parameters at the top of main Bicep file to use parameters.json

### ISSUE THREAD

**Issue by gbeaud** [Azure/bicep-registry-modules#274]
### Module path

https://github.com/Azure/bicep-registry-modules/blob/main/modules/lz/sub-vending/README.md

### Bicep version

CLI 0.15.31

### Describe the bug

- When using the public registry module and the main.bicep you provide (e.g. the one for Hub&Spoke + peering), it's working fine when deploying with parameters directly in the main file but when trying to deploy with the parameter file, it fails because the main.bicep doesn't declare the parameters at the top of the file
- I'm deploying using PowerShell with New-AzManagementGroupDeployment @inputObject
- The fix is easy (adding parameters in main.bicep)

### To reproduce

- Deploy the landing zone vending with the main provided in example here []((https://github.com/Azure/bicep-registry-modules/blob/main/modules/lz/sub-vending/README.md#example-3---subscription-creation--management-group-placement-and-create-virtual-network-and-peering-to-virtual-network))
- Add the parameter file when deploying with New-AzManagementGroupDeployment @inputObject

### Relevant log output

```Shell
Line |
   9 |    New-AzManagementGroupDeployment @inputObject -WhatIf
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  InvalidTemplate - Long running operation failed with status 'Failed'. Additional Info:'Deployment template validation failed: 'The template parameters      
     | 'virtualNetworkName, virtualNetworkUseRemoteGateways, subscriptionTags, disableTelemetry, subscriptionAliasEnabled, virtualNetworkResourceGroupLockEnabled,  
     | existingSubscriptionId, virtualNetworkResourceGroupName, subscriptionManagementGroupAssociationEnabled, virtualNetworkLocation, virtualNetworkEnabled,       
     | virtualNetworkTags, virtualNetworkPeeringEnabled, virtualNetworkResourceGroupTags, roleAssignments, hubNetworkResourceId, subscriptionManagementGroupId,     
     | virtualNetworkAddressSpace, roleAssignmentEnabled' in the parameters file are not valid; they are not present in the original template and can therefore not 
     | be provided at deployment time. The only supported parameters for this template are 'location'. Please see https://aka.ms/arm-pass-parameter-values for      
     | usage details.'.'
```

**Comment by alex-frankel** [comment]
Can you share the powershell command you invoked including all of the parameters?

@jtracey93 -- can you take a look at this one?

**Comment by jtracey93** [comment]
@gbeaud Can you share some repro steps here as all of those parameters have to be exposed, and are from my scan, in the `main.bicep` module file. 

I note from your commands you shared you where deploying an `Alz.bicep` file in the deployment creation. Did you expose all the parameters there? 

As I think this is actually where the issue lies and not with the module. 

Happy to have a quick teams call on this to investigate further, as always 👍

**Comment by jtracey93** [comment]
Also @gbeaud the reason we don't suggest parameter files here as we are using a `.bicep` file itself and self contained values to deploy the module from the registry, instead of parameter files 👍

But we could add a note on here saying if you are going to use a parameter file you need to expose all the parameters in your calling module. 

But to confirm this is **not a bug in the module** 👍

Cc: @alex-frankel

**Comment by jtracey93** [comment]
Hey @gbeaud,

No worries and likewise 👍

Do you want to create a PR on this topic on this repo that I can review?

### Answers to your questions:

1. "I understand that if there is no logic in the main Bicep file (i.e. if it's just holding parameters and calling a module), then you would not use another .json parameter file, since the main Bicep file is somehow the parameter file, right?" - **correct. Almost like a unofficial bicep parameters file by itself**
2. "I was using .json parameter files all the time (e.g. with your ALZ-Bicep modules) but in the present situation I understand users would make a new main Bicep with new parameters for each new landing zone they want to create, and don't add a .json parameter file, correct? (I see it a bit of a pattern change compared to your other assets)" - **if consuming from the registry then correct that would be my preferred approach. This is not meant to be a clone of ALZ approaches and to be more aligned with the TF module for sub-vending we have so they look and feel the same in all aspects.**

Let us know

Thanks

Jack

**Comment by gbeaud** [comment]
@jtracey93 thanks for the feedback! Crystal clear and yes I'll be honored to make a PR and brag to my colleagues I've contributed to this repo (in a readme file 😂👍)
Cheers

**Comment by jtracey93** [comment]
Looking forward to the PR @gbeaud

**Comment by gbeaud** [comment]
@jtracey93 Not sure you got a request to review my PR since it fails a test, but it should not fail since I only edited a readme so that's weird?

![image](https://user-images.githubusercontent.com/79973892/227511967-dce31c0d-793b-4fcf-aad4-ea4b29a8e270.png)

**Comment by ChrisSidebotham** [comment]
@jtracey93 - Can I get a understanding whether this still persists?

**Comment by jtracey93** [comment]
this is being converted to AVM so will close
