### ISSUE TITLE
Module to Provision Event Hub explicitly within existing Event Hub Namespace. Current AVM Event Hub Namespace Module seems not have option to provision event Hub Namespace and Event hub separately 

### ISSUE THREAD

**Issue by SachinKumar-Insight** [Azure/bicep-registry-modules#2868]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/event-hub/namespace

### Description

The module requirement is designed to provision an Event Hub specifically within an existing Event Hub Namespace. It appears that the current Azure Verified Module (AVM) for the Event Hub Namespace does not provide the option to provision the Event Hub Namespace and Event Hub separately.

There are scenarios where a single Event Hub Namespace could be utilized by multiple applications, each with a distinct Event Hub within it. Therefore, it is essential that application teams have the flexibility to provision an Event Hub according to their specific requirements within the existing Event Hub Namespace.

**Comment by AlexanderSehr** [comment]
Hey @SachinKumar-Insight,
please excuse the delay. The automatic owner-assignment seemed to have failed. On that note, @elanzel please take a look and tirage the issue when you get the chance :)

**Comment by elanzel** [comment]
Hi @SachinKumar-Insight if i understand in the right way your request, actually when we deploy an eventhub name space by the AVM module we need also to deploy at least one eventhub, as the eventhub name is mandatory.
You are asking to be able to deploy an empty eventhub namespace and to have the eventhub not mandatory, so you can choose to deploy it or not. Is it?
If this is the case i wonder why should you deploy an event hub namespace without an eventhub in it?

**Comment by AlexanderSehr** [comment]
Hey @SachinKumar-Insight,
this sounds then strongly related to 
- #1933
- #1390
- #2899
- https://github.com/Azure/Azure-Verified-Modules/issues/578
- https://github.com/Azure/Azure-Verified-Modules/issues/747

next to others in that you'd like to directly deploy a child module (in this case event hub) instead of going via its parent (in this case namespace), correct? 

If the case, then (like in the issues mentioned above) your ask is an absolute valid and you're in good company. It's an issue which we solved in CARML back in the day (predecessor of AVM), but had to compromise on when moving into the Public Bicep Registry.
Long story short, there are diverse manual steps involved when publishing a module for the first time, which is quite a hurdle for us when it comes to child-modules specifically as there are quite a few per resource provider. 
We plan to enable this in the future somewhow by lowering that hurdle, but for the time being, you'd only be able to deploy child-modules via their parent from the Public Registry - unless you copy the source-code into your local repository.

I'm pretty sure that's not the answer you're looking for, but the best we can provide at this time. 👀 

cc: @jtracey93, @matebarabas, @eriqua, @ChrisSidebotham (for awareness).

**Comment by SachinKumar-Insight** [comment]
Hey @AlexanderSehr , 

Yes, I would like to have the option for direct child module deployment. Thank you for including this request as a future improvement. I look forward to it. Thanks again.

**Comment by AlexanderSehr** [comment]
I sincerely hope we can get this sorted rather sooner than later. It was super useful in CARML :)
I'm faily certain we'll track this somewhere and I'll link your issue to it and close it here. 💪
