### ISSUE TITLE
[AVM Module Issue]: DCR 'kind' should allow being undefined to support both Windows and Linux.

### ISSUE THREAD

**Issue by jagiraud** [Azure/bicep-registry-modules#3071]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/insights/data-collection-rule

### (Optional) Module Version

0.2.0

### Description

Property `Kind` is optional but defined with default value `Linux` in the template. 
This property should be optional without a default value to support xPlat (all) scenarios. 

![image](https://github.com/user-attachments/assets/7fd66583-d6c6-4c46-9a82-123f00c8922d)

**Comment by krbar** [comment]
@jagiraud thanks for reporting, I will take care of it

**Comment by krbar** [comment]
@jagiraud It turns out to be more complicated because the Resource provider does not accept the value `kind: null` or `kind: ''`, but expects the "kind" to not be present in the module at all when creating a cross-platform Data Collection Rule. I've created a ticket with the product group. I will keep the issue updated

**Comment by krbar** [comment]
@jagiraud The update is implemented in the PR (see above) in review. Once the module is published, you can deploy a cross-platform DCR using the param `dataCollectionRuleProperties.kind: 'All'`
