### ISSUE TITLE
[AVM Question/Feedback]: Using (remote) Bicep registry modules takes longer than local modules

### ISSUE THREAD

**Issue by kamfaima** [Azure/bicep-registry-modules#3359]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Just curious why using AVM modules to deploy a resource takes longer than using a local module? In my scenario, when deploying 21 IP groups from a template referencing the Bicep registry (AVM) it takes roughly 1 min 8 seconds. When I use a local module it takes 38 seconds—roughly half.

Is it because when using AVM, the template has to go over the internet to the Bicep registry, which in turn needs to call the resource provider, again over the internet? Whereas when using local modules, it only needs to call the resource provider—effectively one hop less?

I have anecdotal evidence from others in my team that using AVM to deploy other resources also increases the overall deployment time, so it's not limited to just IP groups.

**Comment by kamfaima** [comment]
> When you say 'local', do you mean you have a local template that deploys IPs via a native `resource myIPs 'Microsoft.Network/publicIP@2024-04-01' = {}` block

Sorry for the confusion! Yes, what you quoted above is what I mean by "local" (module).

The other, slower way, is if I use the Bicep public registry directly from my templates, so `module resource 'br/public:avm/res/network/public-ip-address:0.6.0' = {}`

**Comment by AlexanderSehr** [comment]
Thanks for elaborating. In that case the answer is relatively easy - but be warned, it won't be satisfying 😉

The short of it is that native bicep `resource (...)` deployments are **always** faster than their `module (...)` counterpart. While it may make a small difference in the latter case whether it's a local file reference or a private/public registory (or template spec) reference, the difference will be minimal.

Now the $42 question is why a `module` deployment is slower, and the answer is: _'Because it creates a full-blown 'deployments' object in Azure'_ 
![image](https://github.com/user-attachments/assets/8723e740-8006-4d1a-9c76-a63e1f656124)

While great for tracking, troubleshooting, tracing and understanding deployment structure, the creation of a deployment object always takes a few seconds, and the more 'deployments' you have, the longer it takes for your workload to be rolled out. 

Truth be told, for big deployments / services this may not matter much. If it now takes 30 minutes or 35 minutes usually doesn matter. But for workloads where you deploy hundrets of services (e.g., policy assignments) this can make a bit difference. So much so that the deployment of 200 policy-assignments using raw bicep may take 2 minutes, while using a module that creates one deployment per policy-assignment may take 30 minutes. (mind you, those are fictious numbers I just made up to illustrate my point).

Personally, when I deploy workloads I use module probably 95% of the time as I just can't be bothered 😄 Just when it comes to very small resources (role assignments, policy assignments, resource groups, etc.) and if those are deployed on scale, I'd always opt for a native `resource` deployment.

PS: Mind you that sometimes you cannot use a native `resource` deployment. Especially when implementing loops in loops, or multi-scoped deployments. But if you can, simply try to not artificially perform more 'module' deployment than needed. 

I hope the above provided a bit of context (:
