### ISSUE TITLE
[AVM Module Issue]: Azure Front Door - Standard/Premium - Cannot access custom domain validation TXT values

### ISSUE THREAD

**Issue by hurricane766** [Azure/bicep-registry-modules#3371]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/res/cdn/profile

### (Optional) Module Version

0.5.0

### Description

In order to validate a custom domain, a TXT entry has to be added to the DNS record for the custom domain.

It would be helpful if the AVM module could output these values.

This quick-start example shows how to access these values: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.cdn/front-door-standard-premium-custom-domain/main.bicep

**Comment by gbeaud** [comment]
Hi @hurricane766, my apologies for the late reply and thanks for providing the example! So concretely what you would like, are these 3 below lines added to the customdomain module here, right? https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cdn/profile/customdomain/main.bicep

```
output customDomainValidationDnsTxtRecordName string = '_dnsauth.${customDomain.properties.hostName}'
output customDomainValidationDnsTxtRecordValue string = customDomain.properties.validationProperties.validationToken
output customDomainValidationExpiry string = customDomain.properties.validationProperties.expirationDate
```

**Comment by hurricane766** [comment]
Hi @gbeaud, thank you for looking at this! 

Yes, I believe that would help, but would there also need to be an output from the [main profile module](https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/cdn/profile/main.bicep)? I'm guessing an array of the validationProperties (one item for each custom domain).

The ultimate would be if this AVM could update the DNSZone with the TXT records and initialize the verification process... I don't know if that's out of scope for what AVMs usually do, but it is a requirement to get it all working.

**Comment by gbeaud** [comment]
Hi @hurricane766, thanks for your patience, I had to get back to the core team to verify if your request falls within the specifications of AVM; unfortunately updating the DNS zone with the TXT record is out of scope of a resource module because it interacts with resources outside of the CDN profile, here the DNS record. It would however qualify as a "pattern module": https://azure.github.io/Azure-Verified-Modules/indexes/bicep/bicep-pattern-modules/.

You can find an example of code to create such a TXT record here: https://github.com/Azure/azure-quickstart-templates/blob/master/quickstarts/microsoft.cdn/front-door-standard-premium-custom-domain-azure-dns/main.bicep

```
resource validationTxtRecord 'Microsoft.Network/dnsZones/TXT@2018-05-01' = {
  parent: dnsZone
  name: '_dnsauth.${cnameRecordName}'
  properties: {
    TTL: dnsRecordTimeToLive
    TXTRecords: [
      {
        value: [
          customDomain.properties.validationProperties.validationToken
        ]
      }
    ]
  }
}
```

I will provide the outputs you're asking for (TxtRecordName, TxtRecordValue, ValidationExpiry) and aim to provide them as output from the main profile module as an array of validation properties like you propose. Please allow me some time because I will be out of office the next two weeks but rest assured that your request will be treated - thanks! 😊👍

**Comment by hurricane766** [comment]
Hi @gbeaud 😃 Thank you for the follow up, and I agree it makes more sense as a pattern module. One step at a time I guess... 😞 😆 

Thanks again!

**Comment by nitinitare** [comment]
@gbeaud Also can we output the endpoint hostname, it is required for cname record creation.  
output frontDoorEndpointHostName string = endpoint.properties.hostName

**Comment by gbeaud** [comment]
@nitinitare yes sure I will look into this

**Comment by nitinitare** [comment]
@gbeaud When you are planning to implement this?

**Comment by gbeaud** [comment]
@nitinitare I'm aiming for end of the year / early next year; sorry for the delay I'm heavily loaded right now but feel free to propose a PR if you want to accelerate this 😊👍
