### ISSUE TITLE
[AVM Module Issue]: Data sink issue when using diagnosticSettings with search-service module

### ISSUE THREAD

**Issue by pamelafox** [Azure/bicep-registry-modules#3407]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/search/search-service

### (Optional) Module Version

0.7.1

### Description

I am using the module like this:

```bicep
module searchService 'br/public:avm/res/search/search-service:0.7.1' = {
  name: 'search-service'
  scope: searchServiceResourceGroup
  params: {
    name: !empty(searchServiceName) ? searchServiceName : 'gptkb-${resourceToken}'
    location: !empty(searchServiceLocation) ? searchServiceLocation : location
    tags: tags
    disableLocalAuth: true
    sku: searchServiceSkuName
    semanticSearch: actualSearchServiceSemanticRankerLevel
    diagnosticSettings: [
      {
        workspaceResourceId: monitoring.outputs.logAnalyticsWorkspaceId
      }
    ]
  }
}
```

It worked on the first deploy, but I get this error on the second deploy:

```
Deployment Error Details:
Conflict: Data sink '/subscriptions/d6957007-e9ca-4fca-ab8d-38a11be9656d/resourceGroups/rg-pf-voicerag/providers/Microsoft.OperationalInsights/workspaces/log-mkgwky6acxdmg' is already used in diagnostic setting 'gptkb-mkgwky6acxdmg-diagnostics' for category 'OperationLogs'. Data sinks can't be reused in different settings on the same category for the same resource.
```

I'm just going to remove the diagnostic setting for now.

### (Optional) Correlation Id

fc57f154533cbff7fb862f7f200e1a91

**Comment by krbar** [comment]
@pamelafox thanks for reporting, I will look into it.

**Comment by krbar** [comment]
@pamelafox I think it is not a module issue. This error occurs when you try to create two diagnostic settings sending the same category of logs/metrics to the same Log Analytic workspace. 

Going back to your example: 
When I deploy your code snipped twice, the error doesn’t occur, because both deployments create a diagnostic setting with the same (default) name: `<searchservicename>-diagnosticSettings`, which is no problem.

But I can produce the error with following steps:
-	First deployment of the search service (using your code snippet)
-	Manually delete diagnostic settings created by deployment
-	Manually create a similar diagnostic setting, but with a different name
-	Then second deployment using the template will fail, because it tries to deploy diagnostic settings with the default name.

To resolve it, just delete all diagnostic settings from the search service and re-deploy the template.

**Comment by pamelafox** [comment]
Thanks for taking a look! That may have been the issue since I was porting from our custom modules to avm.
