### ISSUE TITLE
[AVM Module Issue]: Feature request to create subscription in correct management group directly

### ISSUE THREAD

**Issue by RS-MPersson** [Azure/bicep-registry-modules#3443]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/ptn/lz/sub-vending

### (Optional) Module Version

0.1.4

### Description

Feature request is related to intermittent problem with move subscription to management group step during creation of new subscription. The issue is probably due to that permission inheritance is not completed in the platform (depending on the load in Azure).

**Suggestion**: Introduce the possibility to create the subscription in the correct management group location directly in the subscriptionAlias module.

Maybe the existing parameter **subscriptionManagementGroupId** in combination with **subscriptionManagementGroupAssociationEnabled** set to false could be used to achieve this?

Link to the specification https://learn.microsoft.com/en-us/azure/templates/microsoft.subscription/2021-10-01/aliases?pivots=deployment-language-bicep#resource-format where the option managementGroupId is available to use for this.

**Comment by jtracey93** [comment]
Hey @RS-MPersson,

Sorry to hear you are getting intermittent issues with this part of the module. Have you got any correlation IDs and/or error messages you can share so we can investigate further?

We can indeed look at doing something with `properties.additionalProperties.managementGroupId` in the module where we create the subscription. However, it is a WORM (Write Once Read Many) style property and also happens post the subscription being created after an unspecified duration, the subscription still actually gets created in the tenants default management group and then a move operation happens, triggered by the resource provider that backs the `Microsoft.subscription/aliases` API/resource.

So it may not actually solve it and can then introduce confusion as if you change the value you pass to the property, it wont actually update the management group its linked to.

I'd like to dig a little deeper to see if the replication is actually the issue here, please share some correlation IDs so we can take a further look 👍 

Thanks

Jack

#RR

**Comment by RS-MPersson** [comment]
Hi @jtracey93 

Thank you for the quick response.

Here are correlation IDs
989e4bfe-6783-490d-8ac8-fa319d2cf263
0473a4f8-021c-4475-ac00-eed6f007584f

Error message: 
![image](https://github.com/user-attachments/assets/64091f13-86a5-4dcc-9da0-94088aafcecd)

If we rerun the deployment against existing subscription after a couple of minutes everything works, so the permissions set is working.

**Comment by jtracey93** [comment]
Thanks for the correlation IDs @RS-MPersson. I have checked them out and they do both indeed seem like RBAC replication delay issues :( 

What are your thoughts on my details around the `properties.additionalProperties.managementGroupId` on the `Microsoft.subscription/aliases` resource?

It'd be great if we had a retry feature in ARM/Bicep - which is already logged as an ask here https://github.com/Azure/bicep/issues/1013

An alternative is to maybe introduce a "delay" function into the module, like we have done in the ALZ portal experience to give it a chance to replicate before trying again - see https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslzArm.json#L2395-L2421

Whats your thoughts? 

#RR

**Comment by RS-MPersson** [comment]
@jtracey93 I'm fine with keeping the current move LZ scenario if there would be an option to introduce the delay function to make sure that the replication is completed. Based on when the issue for retry option in Bicep was logged it would be faster to introduce the delay function in subvending module.

We're currently stuck going live with our fully automated ServiceNow -> provisioned LZ until the delay is solved. Would it be possible for you to give an estimate of when a delay function could be in place?

P.S. I have run into the same issue in automations that I built before subvending module existed. And I solved it then with a delay in 60 seconds.

**Comment by jtracey93** [comment]
Hey @RS-MPersson,

We could probably get something out within a week if not sooner 👍 

The question is now, how do we introduce the delay:

1. Via serialized (batchSize: 1) empty ARM deployments just like https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslzArm.json#L2395-L2421
    - Obviously expose the loop total count as a parameter so it can be tweaked by consumers 
2. Or in a fancier way like I have documented for VWAN here with deployment scripts: https://learn.microsoft.com/en-us/azure/architecture/guide/devops/deployment-scripts-property-check
    - e.g. we'd check for the RBAC assignments have been inherited before trying to move the subscription etc.

Option 1 is easy and fast to implement, doesnt massively impact deployment total length and complexity, but getting the delay length right will need a bit of trial and error as this issue is intermittent. Unless, you have any data on how long it roughly takes?

Option 2 is a slicker approach but is more complex and will take a bit longer to implement.

There is also an option 3 and thats to investigate this with the Management Groups PG a little more to see if there is something they can do on their side to improve this reliability of the operation

Thoughts @RS-MPersson & also @sebassem?

#RR

**Comment by RS-MPersson** [comment]
@jtracey93  If I recall it correctly deployment scripts leaves some resources behind, which I'm not a big fan of. Is is possible to clean automatically after deployment?

If PG for management groups could solve the root cause for the problem that would of course be the best solution. But maybe that is a longer time frame?

I'm fine with option 1 if you find it suitable and from previous testing 60 seconds should be fine to delay.

**Comment by sebassem** [comment]
> Hey [@RS-MPersson](https://github.com/RS-MPersson),
> 
> We could probably get something out within a week if not sooner 👍
> 
> The question is now, how do we introduce the delay:
> 
> 1. Via serialized (batchSize: 1) empty ARM deployments just like https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslzArm.json#L2395-L2421
>    
>    * Obviously expose the loop total count as a parameter so it can be tweaked by consumers
> 2. Or in a fancier way like I have documented for VWAN here with deployment scripts: https://learn.microsoft.com/en-us/azure/architecture/guide/devops/deployment-scripts-property-check
>    
>    * e.g. we'd check for the RBAC assignments have been inherited before trying to move the subscription etc.
> 
> Option 1 is easy and fast to implement, doesnt massively impact deployment total length and complexity, but getting the delay length right will need a bit of trial and error as this issue is intermittent. Unless, you have any data on how long it roughly takes?
> 
> Option 2 is a slicker approach but is more complex and will take a bit longer to implement.
> 
> There is also an option 3 and thats to investigate this with the Management Groups PG a little more to see if there is something they can do on their side to improve this reliability of the operation
> 
> Thoughts [@RS-MPersson](https://github.com/RS-MPersson) & also [@sebassem](https://github.com/sebassem)?
> 
> #RR

I agree with option 1 since its low/no impact and faster to implement.

**Comment by jtracey93** [comment]
Thanks both @RS-MPersson & @sebassem ill get on with option 1 as a first step

**Comment by jtracey93** [comment]
@RS-MPersson, new version is rolling out as part of #3491 where a new param has been introduced called `managementGroupAssociationDelayCount` with a default of `15` sequential loops which makes it take about 45-60 seconds before trying to move the subscription. But you can pass in your own value as you see fit if need to tweak

**Comment by jtracey93** [comment]
version `0.1.6`  now available
