### ISSUE TITLE
[AVM Module Issue]: subnet.privateEndpointNetworkPolicies doesn't support all available options

### ISSUE THREAD

**Issue by sahinad** [Azure/bicep-registry-modules#3586]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/network/virtual-network

### Description

Hi,

When deploying a subnet, the field privateEndpointNetworkPolicies accepts the values below.

![Image](https://github.com/user-attachments/assets/8cf49843-f180-4fa5-aba6-bfa3f019df4c)

However, we have other options on the Azure portal shown as below.

![Image](https://github.com/user-attachments/assets/8f985ecb-8b1c-475e-9078-fe50977f851a)

Is this on purpose or is it a bug?

**Comment by AlexanderSehr** [comment]
Good day @sahinad,
actually the answer is neither. The module currently has no owner in AVM which means we're dependent on community contributions and or a small group of core maintainers to address issues & open pull requests (which in turn would be reviewed by the maintainers on behalf of the module owner).
The feature in question may be something that was changed with an API-version update since the property was updated last. So, updating it may absolutely make sense.

**Comment by sahinad** [comment]
Cool! I can maybe help with this.

**Comment by AlexanderSehr** [comment]
> Cool! I can maybe help with this.

Got you covered. Thank you @sahinad 💪
