### ISSUE TITLE
[AVM Module Issue]: lz-sub-vending: Feature request NSG to be deployed with Virtual Network and Virtual Network Flow Logs

### ISSUE THREAD

**Issue by jantorep** [Azure/bicep-registry-modules#3679]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Module Name

avm/ptn/lz/sub-vending

### (Optional) Module Version

0.2.1

### Description

Hello

I am missing the feature to add a NSG during deployment of the VNET for the vnet that is beeing deployed. This is a simple add the parameter and add it in to the deployment process. It already does this for the DS resources that is beeing created.

Also can we get Virtual Network Flow Logs enabled automatically and send to correct Log Analytics Workspace and Storage Account?

Regards
Jan-Tore Pedersen

**Comment by sebassem** [comment]
@jantorep  Thanks for suggesting those features. Sub-vending only creates a virtual network without any subnets as this should be done by the workload team so assigning NSGs cannot be part of this module since its usually assigned to subnets. With regards to vNet flow logs, this is something we are still assessing how it will be implemented in ALZ but most probably this should be configured and enforced using policies
