### ISSUE TITLE
[AVM Question/Feedback]: When will newer MongoDB server versions than 4.2 be supported for CosmosDB?

### ISSUE THREAD

**Issue by aTTraX** [Azure/bicep-registry-modules#3709]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Hi guys,

we use AVM for our infrastructure and want to update our CosmosDB to support the MongoDB server version 7.0, but it´s limited to max 4.2 as you can see here:
[AVM document-db/database-account#parameter-serverversion](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/document-db/database-account#parameter-serverversion)

Is there a reason why you only allow the following serverVersions:
Allowed:
[
  '3.2'
  '3.6'
  '4.0'
  '4.2'
]

And is there an update for newer version planned?

Thanks in advance!

Markus

**Comment by FallenHoot** [comment]
It looks like you're aiming to use MongoDB version 7, but currently, the [databaseaccounts AVM module](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/document-db/database-account) only supports MongoDB version 6 with the Microsoft.DocumentDB/databaseAccounts@2023-04-15 API. To enable MongoDB 7, you'll need to use the [mongo-cluster AVM module](https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/document-db/mongo-cluster), which defaults to the latest MongoDB version and doesn’t require specifying a version parameter.

If you're set on using the databaseaccounts module, an upgrade to the Microsoft.DocumentDB/databaseAccounts@2024-05-15 API is necessary to support MongoDB version 6 fully. However, for MongoDB version 7, switching to the mongo-cluster module would be the most efficient approach since it’s already configured for this version.

Let me know if you need further guidance on this!

**Comment by aTTraX** [comment]
Hey @FallenHoot, thank you very much for your fast reply. We will consider switching to vCore based.

**Comment by aTTraX** [comment]
Hi @FallenHoot, there is the possibility to manually set the RU-based MongoDB server version to MongoDB 7 via the portal in the CosmosDB-Features section.
Does this manual update interfere with the future AVM update when version 7 is ready for RU via AVM?
Do you know if there is a plan to release server version 7 in the next time?

**Comment by aTTraX** [comment]
> When trying over Azure Portal, it is possible to select version 7.0 also for RUA approach. Don't have instance provisioned now but it seems there is a valid version of Microsoft.DocumentDB/databaseAccounts supporting 7.0

Exactly and it also seem to work because one of our developers upgraded via Portal to version 7, that´s why I ask if it has any influence on IaC based deployment in the future or not?

**Comment by dmusic** [comment]
> > When trying over Azure Portal, it is possible to select version 7.0 also for RUA approach. Don't have instance provisioned now but it seems there is a valid version of Microsoft.DocumentDB/databaseAccounts supporting 7.0
> 
> Exactly and it also seem to work because one of our developers upgraded via Portal to version 7, that´s why I ask if it has any influence on IaC based deployment in the future or not?

Well, it should be just an update within allowed values for MongoDB RU. I understand that vCore solution is the future one and best practice but why not supporting what is supported in official Azure Portal.

**Comment by FallenHoot** [comment]
I can only rely on the [official documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.documentdb/2024-05-15/databaseaccounts?pivots=deployment-language-bicep#apiproperties), which states that only version 6.0 is supported. Although RU and vCore models support version 7 as of July 2024, the API (current as of May 2024) is limited to version 6. This applies across all deployment methods—AVM, Terraform, ARM, etc.—because the API does not permit deployment with version 7.

Here’s the error message you will encounter if you try to deploy the latest API with `ServerVersion  7`:

```json
{
  "status": "Failed",
  "error": {
    "code": "BadRequest",
    "message": "ServerVersion is not allowed for this API type.\r\nActivityId: 9cb453bc-23db-4bf7-96f2-e92f5fe9630d, Microsoft.Azure.Documents.Common/2.14.0"
  }
}
```

The best course of action is for me to check with the program manager for Cosmos DB for MongoDB about why the version published hasn't been updated. Nonetheless, we’ll need to create a PR for the AVM to reflect this. Something @Azure/avm-res-documentdb-databaseaccount-module-owners-bicep needs to look into.

**Comment by FallenHoot** [comment]
This is currently being reviewed by Product Manager, and I am waiting for confirmation when the latest ARM API can be used.

**Comment by AlexanderSehr** [comment]
Hey folks, 
somehow this issue was not created as a module issue and as such was not auto-assigned to the module owners @bryansan-msft  & @seesharprun. I just assigned the two and would ask them to also take a look to triage the issue :)
Thanks @FallenHoot for the active involvement 💪
