### ISSUE TITLE
[AVM Question/Feedback]:

### ISSUE THREAD

**Issue by gsuttie** [Azure/bicep-registry-modules#3859]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

When deploying a web app using Bicep i see this a lot of the time

![Image](https://github.com/user-attachments/assets/b76fbb85-1e5c-4d4c-81fd-3c80b090352d)

How do we get it to select the stack correctly using bicep?

If I select the correct stack it selects the write version, so if its net it chooses the right .Net Version underneath but it always shows Stack as empty

**Comment by pankajagrawal16** [comment]
Hi @gsuttie Thanks for opening the issue.

As I understand, you having troubles finding configurations that would be needed by sites bicep resource so that the portal correctly display the stack settings?

This is not something which is related to Azure verified modules for sites but related to native bicep resource for sites. 

Regardless I can see there was similar issue which was opened on bicep repo which is already answered https://github.com/Azure/bicep/discussions/6324

Please check. You probably need to use combination of CURRENT_STACK in siteConfig for metadata
