### ISSUE TITLE
Should we require `newOrExisting` pattern for public modules where applicable?

### ISSUE THREAD

**Issue by alex-frankel** [Azure/bicep-registry-modules#68]
Context is from here:
https://github.com/Azure/bicep-registry-modules/pull/62#discussion_r844222176

Basically, for modules that have "prereq" resources, should we require modules to optionally allow either a new resource or an existing one?

This is the case for using a managed identity, which we will see for any resources that support MI. I suspect there other cases - existing Log Analytics workspace, storage accounts, etc.

**Comment by shenglol** [comment]
I think we should require this pattern. Let me mention this in the contribution guide.

**Comment by alex-frankel** [comment]
@bmoore-msft -- would also be curious to get your thoughts on this topic

**Comment by bmoore-msft** [comment]
I think the key point you make is "where applicable"... IDK if we should require outright since it doesn't always make sense.  IOW, let the scenario drive it - if we miss one, we'll get feedback and can always add it (or take a PR for it).

the MSI scenario from #62 is a great example of the scenario...  it's also common to use existing vnet, less common to use existing publicIps and even less common to use existing NICs.  If I have a module that has 30 resources, probably doesn't make sense for all of those to be optional.  So maybe we just need the correct "framing":

- some modules will "require" an existing resource (that's the point of the module) - e.g. pulling a cert from KeyVault
- some modules will be only about the resource being provided (i.e. require "new")
- "supporting resources", when created in the template should also have the option for existing - it's tricky to define supporting, e.g. is a parent resource "supporting"?  My guess is most module authors will know this when they see it...
- ???

Also, we should establish the pattern/model for the newOrExisting scenario.  I.e. what params are needed (rg, name, switch), what are the names of those params, what is the default of the switch param? - and also keep in mind what the code should look like, perhaps in the future, if we simplify the pattern.  I.e. if we still have to do this everywhere:
```bicep
     id: newOrExisting ? exsitingResource.id : newResource.id
```
instead of:
```bicep
    id: someResource.id
```
maybe for now we want to be *very* scenario driven so we don't proliferate a less elegant pattern.  And then have to have authors think about more like - if we need multiple symoblic names, should those names be patterned as well?  And how do we enforce it, etc...

my $0.04 (inflation)
