### ISSUE TITLE
[AVM Question/Feedback]: Clarify use of modules in `avm` folder from those in `modules` folder.

### ISSUE THREAD

**Issue by kamfaima** [Azure/bicep-registry-modules#687]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

I'd like to understand why there are sometimes two versions of the same code in this repo. For example, code for private DNS zones is in two locations:

- `avm/res/network/private-dns-zone/main.bicep` (added on Oct 24, updated on Nov 27)
- `modules/network/private-dns-zone/main.bicep` (added on Aug 31)

The code in each of these modules is very different. In this case,`main.bicep` in the `avm` folder has more functionality than `main.bicep` in the `modules` folder.

I thought the intention of consolidating all the code (from CARML) was to ensure just a single Microsoft endorsed library (i.e. this repo) in which the module could be consumed in code by using either:

- `module dnsZone 'br/public:network/private-dns-zone:1.0.1' = {}` syntax
- `module dnsZone 'modules/network/private-dns-zone/main.bicep' = {}` syntax (i.e. referencing the module locally after repo has been cloned)

I would have thought either method would refer to the same underlying Bicep module—instead, it looks like some modules have two different code bases, e.g. the private DNS zone code.

Or is this simply a case of the newly migrated CARML module into AVM not yet being added into the Bicep public registry and I just need to wait until the module in the Bicep public registry is updated with that in the `avm` folder?

Thank you for you time! 🙏

**Comment by AlexanderSehr** [comment]
Hey @kamfaima,
a fair question. Let me try to explain the current setup as well as I can (given that I'm engaged in the CARML migration).

First and foremost, let me acknowledge you're absolutely right. It's a bit confusing that there are 2 version of modules in some instances - and given that we have only migrated about 30% of the CAMRL module to date, more overlaps are to be expected. And that the currently published module references do NOT point to the same module, but to their corresponding instance (as per the `avm` & `modules` folders).

## Context
So why is that the case? The reason is, that we aimed to migrate CARML to the public registry for the longest time, but struggeled to do so for a couple of reasons, ultimately bring the efforts to a hold.

On a different note, the intiative called 'Azure Verified Modules' is a bit broader than just this effort as it is intended as a standardized code-base that covers both Terraform and Bicep (with CARML providing the code base and being a major influence on it's [design specs](https://aka.ms/avm)). 
While working this out, we aim to get the current CARML code base aligned with these specs & migrated to the Public Registry as fast as possible (as evident by the big banner on the CARML repository's [front page](aka.ms/carml)). 

While doing so, we did not want to conflict in any way with what is already published in the public registry's `modules` folder and try and make it clear that the AVM modules follow a rather different / strict set of design principals. Mind you that the currently published modules of the `modules` folder are already used, so we cannot (and won't) simply replace them with an AVM counterpart. 

That may sound a bit cryptic, so let me use an example. Any module in AVM is supposed to follow a very strict 'providerNamespace/resourceType' structure in which each module can deploy exactly 1 instance of a resource in addition to any amount of children (e.g. containers for a storage account) and other extension resources such as RBAC, Private Endpoints, Diagnostic Settings etc. etc.
In comparison, the modules in the `modules` folder do not have this restriction. They still need to meet the requirements of the BRM tool & registry-CI, but you will quickly find that many modules deploy specific scenarios instead of deploying 'only' a resource.

Maybe somewhere down the line, the avm & modules folder will converge, and any module that is not a simple resource type will simply land in the `avm/ptn` folder (`ptn` for `pattern`). But that's to soon to say and I don't want to imply that any discussions on that happened yet. However, we'll get to resolve the current situation somewhow.

## So where does this all leave you as a consumer?
Well, we want to make sure any module in the `avm` folder follows the schema linked above. As such, if you reference any module with the `avm.` prefix, you will find they're all following the same design principals (similar to what we did in CARML). So if you want to built a solution and want to make use of these features / re-use a consistent code base, great.
However, this is not supposed to say the modules in the `modules` folder have any less value. They're actually very neat and simply follow the design principal of their original creator. They're also usually a lot more streamlined as they don't need to aspire to implementing e.g. all properties a resource type would offer etc.

## Lifecycle
As per your last question, no - you don't have to wait. As stated above, we're making an effort to get the CARML modules migrated as 'refactored' AVM modules as fast as possible. This will leave the CARML repository with providing a CI for customers to use - while the modules will live in the Public Bicep Registry repository and will be published to the Public Registry. If a customer were to inner-source them, they could simply copy the `avm` folder and if desired plug & play it into the CARML CI (at least that's what I want to ensure once the migration concluded).
The modules in the `modules` folder exist and will continue to exist with their own lifecycle, as per the original contributor's intent. 

I hoped that helped to clarify this a little bit, but please feel invited to ask follow-up questions if anything remains unclear. If not, feel free to close the issue :) .

**Comment by AlexanderSehr** [comment]
> g that detailed response, it has certainly made clearer which module (`avm` vs `module`) source to use with/for our own code base moving forward.
> 
> I noticed that the `README.md` for a lot (or all?) of the `avm` modules mention being able to call the module using the `br/public:avm/res/key-vault/vault:<version>` syntax. However, unlike t

Happy to help @kamfaima .

Regaring the version, 2 nuggets:
1. General usage: The VSCode extension for Bicep should automatically suggest you all versions that are available for a module.
    ![image](https://github.com/Azure/bicep-registry-modules/assets/5365358/6f749db0-c244-474f-b90a-c8254bc26ba7)
1. The `<version>` 'issue' was raised in the past. As in CARML we used to have a dummy `1.0.0` in the usage examples. However, as those don't exist yet (and may be misleading if you think it's like a recommended version), we pivoted to a placeholder `<version>` to get started. This was done to make sure the user knows you have to replace this version with the actual version.

    There actually was a PR to always show the actual version of the module at the time of publishing the readme in the usage examples. This worked great for like one published version and then started failing the static tests for every time after. The reason was that the readme tool was expecting a new module version for each pipeline run (even if it was just for testing & even though a new version is only created if an update was merged to main). This may sound confusing and it is a little without going into the full context. However, we still plan to sort this out eventually, and the `<version>` placeholder is just a fallback for the time being.

**Comment by kamfaima** [comment]
Oh man, I should've realised the auto-suggestion in VSCode—I just didn't backspace past the `:` in the syntax to bring it up 🤦 

Ok if the `avm` modules can also be referenced from the Bicep public library, then that aligns with my original intention with how we were going to use the code in `modules`. i.e. Moving forward and where applicable, use Microsoft/AVM authored code to (a) save us time; and (b) minimise the number of modules in our own code base.

Thanks again for your time in answering the questions and clarifying everything! 🙏
