### ISSUE TITLE
[AVM Module Issue]:  Unable to deploy storage account due to existing 'requireInfrastructureEncryption' value

### ISSUE THREAD

**Issue by Wesleyrbk** [Azure/bicep-registry-modules#846]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Module Name

avm/res/storage/storage-account

### (Optional) Module Version

0.5.0

### Description

Using the avm module on an existing storage account, whereby the 'requireInfrastructureEncryption' is set to false, mirroring the actual resource on the Azure environment. Causes the following error:

The property 'requireInfrastructureEncryption' was specified in the input, but it cannot be updated as it is read-only.

**Comment by AlexanderSehr** [comment]
Hey @fblix, please note. The issue is located here:
https://github.com/Azure/bicep-registry-modules/blob/a24f69509c25db916c80d70ce7eebbf666f2781c/avm/res/storage/storage-account/main.bicep#L283

where the parameter has a default value of `true`. We may need to change it to a null-default - or at least somehow enable to not set it at all (as also `false` - as per the original post) does cause ARM to complain. 

Imho this is an issue of the provider that should actually look at the value instead of outright blocking it if it wasn't set initially, but nothing we can do about that from the consumer end.

Please note, if we change the value it could happen that PSRule acts up as we're changing the solution to something 'less secure', but let's cross that bridge when we get there.

**Comment by jtracey93** [comment]
@fblix are you able to pick this up and resolve the issue?

**Comment by fblix** [comment]
> @fblix are you able to pick this up and resolve the issue?

yep, gonna take a look as soon as I have some time.

**Comment by fblix** [comment]
So I've taken a look at this issue.

If an existing storage account is old enough, then it does not have the flag `"requireInfrastructureEncryption": true|false` at all.
When you then try to run bicep on it, it tries to set this flag, which fails because the property is not found (obviously).
Any newly created storage account will automatically have this flag, either set to false or true.

Question would be if we want to offer support for such old storage accounts, what do you think @AlexanderSehr ?

**Comment by krbar** [comment]
@Wesleyrbk The module version 0.6.1 should solve this issue. Please keep in mind, that you must set `requireInfrastructureEncryption: false` when deploying over an existing, affected storage account.
